_wandb:
    value:
        cli_version: 0.24.0
        e:
            6c8wk58l4197x6ic2bbq3d9mrnxov47f:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                args:
                    - --max_depth=None
                    - --min_samples_split=6
                    - --n_estimators=200
                codePath: mlops/02_train.py
                codePathLocal: 02_train.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "220138569728"
                email: i.soummar@esi-sba.dz
                executable: /Users/mac/Documents/GitHub/MINI_PROJET_ML/venv/bin/python
                git:
                    commit: 3069b998b1f28d105caa6191479224c87de35ff2
                    remote: https://github.com/Amina212004/MINI_PROJET_ML.git
                host: Macs-MacBook-Air-2.local
                memory:
                    total: "8589934592"
                os: macOS-14.7-arm64-arm-64bit-Mach-O
                program: /Users/mac/Documents/GitHub/MINI_PROJET_ML/mlops/02_train.py
                python: CPython 3.13.2
                root: /Users/mac/Documents/GitHub/MINI_PROJET_ML/mlops
                startedAt: "2026-01-29T15:44:58.153257Z"
                writerId: 6c8wk58l4197x6ic2bbq3d9mrnxov47f
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.13.2
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
max_depth:
    value: null
min_samples_split:
    value: 6
n_estimators:
    value: 200
